<a href="https://colab.research.google.com/github/siddhimane25/Complete-Data-Science-With-Machine-Learning-And-NLP-2024/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
x= torch.tensor([1,2,3,4,5])
print(x)

tensor([1, 2, 3, 4, 5])


In [6]:
y= torch.tensor([
    [1,2],
    [3,4]]
)
print(y)

tensor([[1, 2],
        [3, 4]])


In [8]:
z = torch.zeros(3,2)
print(z)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [7]:
o = torch.ones(2,2)
print(o)

tensor([[1., 1.],
        [1., 1.]])


In [9]:
r = torch.rand(2,2)
print(r)

tensor([[0.8278, 0.8882],
        [0.6231, 0.3696]])


In [11]:
a = torch.tensor([
    [1,2,3],
    [4,5,6]]
)
print(a.shape)

torch.Size([2, 3])


In [12]:
i = torch.tensor([10, 20, 30])
print(i[0])
print(i[1])

tensor(10)
tensor(20)


In [17]:
d_2 = torch.tensor([
    [10,20,30],
    [40,50,60]
])
print(d_2[0, 1])
print(d_2[1,2])

tensor(20)
tensor(60)


In [19]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
print(a + b)
print(a * b)

tensor([5, 7, 9])
tensor([ 4, 10, 18])
